/**
 * ============================================================================
 *  MODULE CONTRACT — 古惑仔：銅鑼灣之龍
 * ============================================================================
 *  This file is the single source of truth for every cross-module API.
 *  Modules talk to each other ONLY through:
 *    1. the interfaces below (reached via `GameContext`), and
 *    2. the typed EventBus (`GameEvents`).
 *  Never import a concrete class from another module's directory. The only
 *  place allowed to do that is the composition root `src/core/GameInstance.ts`.
 *
 *  Extending events from inside your own module is allowed via module
 *  augmentation (do NOT edit this file for that):
 *
 *    declare module '../core/types' {
 *      interface GameEvents { 'mymodule:thing': { foo: number } }
 *    }
 *
 *  ---------------------------------------------------------------------------
 *  WORLD CONVENTIONS (everyone must follow these)
 *  ---------------------------------------------------------------------------
 *  - Units: metres, seconds, radians. Y is up.
 *  - North is -Z, south is +Z, east is +X, west is -X.
 *  - Yaw: an entity with yaw θ faces direction (sin θ, 0, cos θ).
 *    yaw 0 faces +Z (south). object3d.rotation.y === yaw.
 *  - A character facing +Z has its RIGHT side toward -X and LEFT toward +X.
 *  - Camera-relative movement: with camera yaw ψ, forward = (sin ψ, 0, cos ψ),
 *    right = (-cos ψ, 0, sin ψ).
 *
 *  RIG / POSE CONVENTIONS (used by entities + combat animation authoring)
 *  - Bind pose: standing upright, facing +Z, arms hanging straight down at the
 *    sides, legs straight. Every limb bone points along -Y in bind pose.
 *  - Pose values are local Euler rotations (order 'XYZ') in radians, applied
 *    RELATIVE to the bind pose.
 *  - Arms / thighs:  X negative  => swing forward (upperArm X = -π/2 points the
 *                                   arm straight forward; thigh X = -1.2 raises knee)
 *                    upperArmL Z positive / upperArmR Z negative => raise sideways
 *  - Forearm:        X negative  => elbow flexes, hand comes forward/up
 *  - Shin:           X positive  => knee bends (foot goes backward)
 *  - Spine/chest/neck/head: X positive => lean/look forward-down,
 *                           Y positive => twist toward character's LEFT (+X)
 *  - `rootOffset` moves the hips relative to their bind height (e.g. [0,-0.4,0]
 *    for a crouch, [0,-0.85,0] lying on the ground combined with hips X ±π/2).
 * ============================================================================
 */
import type {
  Box3,
  Object3D,
  PerspectiveCamera,
  Scene,
  Vector3,
  WebGLRenderer,
} from 'three';
import type RAPIER from '@dimforge/rapier3d-compat';
import type { EventBus } from './EventBus';

// ---------------------------------------------------------------------------
// Time & systems
// ---------------------------------------------------------------------------

export interface GameTime {
  /** Scaled delta (0 when paused, <1 in bullet time). Use for gameplay. */
  dt: number;
  /** Unscaled wall-clock delta, clamped to 0.1s. Use for UI/audio/camera easing. */
  realDt: number;
  /** Accumulated scaled time. */
  elapsed: number;
  /** Accumulated real time. */
  realElapsed: number;
  frame: number;
}

/**
 * Every long-lived module implements this. Engine calls, per rendered frame:
 *   fixedUpdate(FIXED_DT) 0..n times (followed by a physics step each time)
 *   update(time)          once, in registration order
 *   lateUpdate(time)      once, in registration order (camera goes here)
 * Constructors must ONLY store `ctx`; never touch other systems before init().
 */
export interface GameSystem {
  readonly name: string;
  init(): Promise<void> | void;
  update(time: GameTime): void;
  fixedUpdate?(fixedDt: number): void;
  lateUpdate?(time: GameTime): void;
  dispose?(): void;
}

export const FIXED_DT = 1 / 60;

// ---------------------------------------------------------------------------
// Game state machine
// ---------------------------------------------------------------------------

export type GameModeId =
  | 'boot'
  | 'title'
  | 'freeRoam'
  | 'dialogue'
  | 'cutscene'
  | 'combat'
  | 'heatAction'
  | 'menu'
  | 'shop'
  | 'gameOver'
  | 'credits';

export interface ModePayloads {
  boot: undefined;
  title: undefined;
  freeRoam: undefined;
  dialogue: { dialogueId: string };
  cutscene: { cutsceneId: string };
  combat: { encounterId: string };
  heatAction: { actionId: string; targetId: string };
  menu: { tab?: 'inventory' | 'quests' | 'system' };
  shop: { shopId: ShopId };
  gameOver: undefined;
  credits: undefined;
}

export interface IGameStateMachine {
  readonly mode: GameModeId;
  readonly previous: GameModeId;
  /** Payload passed to the most recent transition. */
  readonly payload: unknown;
  /** Seconds (real time) spent in the current mode. */
  readonly timeInMode: number;
  is(...modes: GameModeId[]): boolean;
  can(to: GameModeId): boolean;
  /** Returns false (and logs a warning) if the transition is not in the table. */
  transition<M extends GameModeId>(to: M, payload?: ModePayloads[M]): boolean;
  /** Return to the mode we were in before the current one (menu/shop close). */
  back(): boolean;
}

// ---------------------------------------------------------------------------
// Engine & rendering
// ---------------------------------------------------------------------------

export interface IRenderPipeline {
  render(time: GameTime): void;
  setSize(width: number, height: number, pixelRatio: number): void;
  /**
   * Named full-screen effects, intensity 0..1. Two kinds:
   *  LEVELS (persist until changed; pipeline smooths towards the target):
   *   'heat'       – heat-action look (desaturate + radial blur + orange rim)
   *   'lowHealth'  – desaturated, pulsing red edges when HP is low
   *   'bulletTime' – chromatic aberration + slight blur during slow-mo
   *  IMPULSES (setting starts a pulse that decays by itself in ~0.35 s):
   *   'damage'     – red vignette hit
   *   'flash'      – white impact flash
   * The combat module drives all of these.
   */
  setEffect(name: RenderEffect, intensity: number): void;
}
export type RenderEffect = 'heat' | 'damage' | 'lowHealth' | 'bulletTime' | 'flash';

/**
 * Concrete class: `new GameEngine(container: HTMLElement, input: IInputManager, physics: IPhysicsWorld)`.
 * Per rendered frame:
 *   input.beginFrame(realDt)
 *   repeat while accumulator ≥ FIXED_DT (max 5):  systems.fixedUpdate(FIXED_DT); physics.step(FIXED_DT)
 *   physics.syncLinked()
 *   systems.update(time)      (registration order)
 *   systems.lateUpdate(time)  (registration order)
 *   renderPipeline.render(time)  (or renderer.render(scene, camera) if none)
 *   input.endFrame()
 * When paused or timeScale = 0, no fixed steps run.
 */
export interface IEngine {
  readonly renderer: WebGLRenderer;
  readonly scene: Scene;
  readonly camera: PerspectiveCamera;
  readonly time: Readonly<GameTime>;
  readonly canvas: HTMLCanvasElement;
  /** Gameplay time multiplier (bullet time). 1 = normal. */
  readonly timeScale: number;
  /** When true, scaled dt is 0 (menus). Real time continues. */
  paused: boolean;
  /**
   * Set time scale. If `realDuration` is given, it automatically eases back to 1
   * after that many real seconds.
   */
  setTimeScale(scale: number, realDuration?: number): void;
  addSystem(system: GameSystem): void;
  setRenderPipeline(pipeline: IRenderPipeline): void;
  readonly renderPipeline: IRenderPipeline | null;
  start(): void;
  stop(): void;
}

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

/**
 * Default bindings (InputManager owns the mapping):
 *  moveForward W/↑  moveBack S/↓  moveLeft A/←  moveRight D/→
 *  sprint Shift     lightAttack J / Mouse0   heavyAttack K / Mouse2
 *  guard L (hold)   dodge Space              interact E
 *  grab G           heatAction F             lockOn Q (toggle)   cycleTarget Tab
 *  pause Escape     inventory I              confirm Enter/Space/E
 *  cancel Escape/Backspace   menuUp W/↑  menuDown S/↓  menuLeft A/←  menuRight D/→
 *  choice1..4 Digit1..4      debug F3
 * Every action also has a touch source, driven by the on-screen controls.
 */
export type InputAction =
  | 'moveForward' | 'moveBack' | 'moveLeft' | 'moveRight'
  | 'sprint' | 'lightAttack' | 'heavyAttack' | 'guard' | 'dodge'
  | 'interact' | 'grab' | 'heatAction' | 'lockOn' | 'cycleTarget'
  | 'pause' | 'inventory' | 'confirm' | 'cancel'
  | 'menuUp' | 'menuDown' | 'menuLeft' | 'menuRight'
  | 'choice1' | 'choice2' | 'choice3' | 'choice4'
  | 'debug';

export interface IInputManager {
  isDown(action: InputAction): boolean;
  /** True only on the frame the action went down (and not yet consumed). */
  wasPressed(action: InputAction): boolean;
  wasReleased(action: InputAction): boolean;
  /**
   * Mark this frame's press as handled so later systems in the same frame do
   * not also react (e.g. the E that closes a dialogue must not re-open it).
   */
  consume(action: InputAction): void;
  /** Was the action pressed within the last `withinSec` real seconds (unconsumed buffer)? Consumes it if true. */
  consumeBuffered(action: InputAction, withinSec: number): boolean;
  /** x = right, y = forward, length ≤ 1. Zero when input is blocked. */
  getMoveVector(): { x: number; y: number };
  /** Mouse or touch-drag delta in pixels since last frame (only while pointerLocked). */
  getLookDelta(): { x: number; y: number };
  /** Human label for the primary binding, e.g. 'J', 'SPACE', 'LMB' (the button face in touch mode). */
  getLabel(action: InputAction): string;
  /** The last pointer was a finger: on-screen controls are in charge. */
  readonly touch: boolean;
  /** On-screen button held/released. Mixes with keys like any other source. */
  setTouchButton(action: InputAction, down: boolean): void;
  /** On-screen stick, x = right, y = forward, length ≤ 1. (0, 0) = let go. */
  setTouchStick(x: number, y: number): void;
  /** On-screen camera drag, in pixels. */
  addTouchLook(dx: number, dy: number): void;
  /** Look input is live: the mouse is captured, or touch mode (which needs no capture). */
  readonly pointerLocked: boolean;
  requestPointerLock(): void;
  exitPointerLock(): void;
  /** Called by the engine. */
  beginFrame(realDt: number): void;
  endFrame(): void;
}

// ---------------------------------------------------------------------------
// Physics
// ---------------------------------------------------------------------------

/** Collision membership bits. Use `interactionGroups(member, filter)`. */
export const CG = {
  STATIC: 0x0001,
  CHARACTER: 0x0002,
  PROP: 0x0004,
  DEBRIS: 0x0008,
  /**
   * Combat arena ring: create with interactionGroups(CG.ARENA, CG.CHARACTER). Character sweeps
   * stop at it; the camera, STATIC raycasts, props and debris pass through.
   */
  ARENA: 0x0010,
  ALL: 0xffff,
} as const;

export function interactionGroups(membership: number, filter: number): number {
  return ((membership & 0xffff) << 16) | (filter & 0xffff);
}

export interface RaycastHit {
  point: Vector3;
  normal: Vector3;
  distance: number;
  collider: RAPIER.Collider;
}

/**
 * Kinematic capsule driven by Rapier's KinematicCharacterController.
 * Collides with STATIC colliders only (characters never block each other or
 * props; EntityManager applies soft separation between characters).
 * Autostep 0.3 m, snap-to-ground 0.3 m, slopes ≤ 45°.
 */
export interface ICharacterBody {
  readonly collider: RAPIER.Collider;
  readonly rigidBody: RAPIER.RigidBody;
  /** Foot position (bottom of capsule). Updated after every move/teleport. */
  readonly position: Vector3;
  readonly grounded: boolean;
  /**
   * Move by `displacement` (metres, for this fixed step) with sliding and step-up.
   * No gravity is applied here — the Character integrates vertical velocity itself.
   */
  move(displacement: Vector3): void;
  teleport(footPosition: Vector3): void;
  /** Disabled bodies don't collide and ignore move(). */
  setEnabled(enabled: boolean): void;
  dispose(): void;
}

export interface IPhysicsWorld {
  readonly rapier: typeof RAPIER;
  readonly world: RAPIER.World;
  /** Static oriented box. `rotationY` in radians. */
  createStaticBox(center: Vector3, halfExtents: Vector3, rotationY?: number): RAPIER.Collider;
  createStaticCylinder(center: Vector3, halfHeight: number, radius: number): RAPIER.Collider;
  /** Ground plane / big slab helper. */
  createStaticTrimesh(vertices: Float32Array, indices: Uint32Array): RAPIER.Collider;
  createCharacterBody(footPosition: Vector3, radius: number, height: number): ICharacterBody;
  /**
   * Dynamic box linked to an Object3D: every frame after the physics step the
   * object's world position/quaternion is copied from the body (object must be a
   * direct child of the scene).
   */
  createDynamicBox(
    object: Object3D,
    halfExtents: Vector3,
    opts?: { mass?: number; friction?: number; restitution?: number; groups?: number; linearDamping?: number; angularDamping?: number },
  ): RAPIER.RigidBody;
  removeBody(body: RAPIER.RigidBody): void;
  raycast(origin: Vector3, dir: Vector3, maxDist: number, groups?: number, excludeCollider?: RAPIER.Collider): RaycastHit | null;
  step(fixedDt: number): void;
  /** Copy dynamic body transforms to linked objects (engine calls after step). */
  syncLinked(): void;
}

// ---------------------------------------------------------------------------
// Camera
// ---------------------------------------------------------------------------

export type CameraMode = 'follow' | 'combat' | 'dialogue' | 'cinematic' | 'orbitShowcase';

export type Vec3Source = Vector3 | (() => Vector3);

export interface CameraShot {
  /** Camera position (static or evaluated every frame). */
  position: Vec3Source;
  lookAt: Vec3Source;
  /** Optional second position/lookAt to interpolate towards over `duration` (dolly). */
  toPosition?: Vec3Source;
  toLookAt?: Vec3Source;
  fov?: number;
  duration: number;
  ease?: EaseName;
  /** If true, duration is measured in real time (ignores bullet time). Default true. */
  realTime?: boolean;
}

export type EaseName = 'linear' | 'inQuad' | 'outQuad' | 'inOutQuad' | 'inCubic' | 'outCubic' | 'inOutCubic' | 'outBack' | 'outExpo';

export interface ICameraRig {
  readonly camera: PerspectiveCamera;
  readonly mode: CameraMode;
  setMode(mode: CameraMode): void;
  /** Object the follow/combat camera tracks (the player). */
  setFollowTarget(target: Object3D): void;
  /** In combat mode, frame this target together with the follow target. */
  setLockTarget(target: Object3D | null): void;
  /** Dialogue framing: over-the-shoulder between two speakers. */
  setDialogueFraming(a: Object3D, b: Object3D): void;
  /** Play shots back-to-back in 'cinematic' mode; resolves when done, then restores the previous mode. */
  playSequence(shots: CameraShot[]): Promise<void>;
  stopSequence(): void;
  shake(intensity: number, duration: number): void;
  /** Brief FOV punch (negative = zoom in) for impacts. */
  punch(fovDelta: number, duration: number): void;
  /** Horizontal orbit yaw — player movement is relative to this. */
  getYaw(): number;
  /** Snap camera behind the follow target (after teleports). */
  snapBehindTarget(): void;
}

// ---------------------------------------------------------------------------
// Audio
// ---------------------------------------------------------------------------

export type SfxId =
  | 'punch_light' | 'punch_heavy' | 'kick' | 'whoosh' | 'whoosh_heavy' | 'block' | 'dodge'
  | 'body_fall' | 'grab' | 'throw' | 'ko' | 'stomp'
  | 'chair_hit' | 'chair_break' | 'cone_hit' | 'bottle_smash' | 'wood_break' | 'metal_clang'
  | 'pickup' | 'drop' | 'footstep' | 'footstep_wet'
  | 'heat_ready' | 'heat_action' | 'slowmo_in' | 'slowmo_out' | 'impact_boom'
  | 'qte_prompt' | 'qte_success' | 'qte_fail'
  | 'ui_move' | 'ui_confirm' | 'ui_cancel' | 'ui_open' | 'ui_close' | 'dialogue_blip'
  | 'money' | 'eat' | 'drink' | 'save' | 'payphone_ring' | 'payphone_pickup' | 'pager_beep'
  | 'tram_bell' | 'car_horn' | 'table_flip' | 'glass_break' | 'crowd_gasp' | 'crowd_cheer'
  | 'boss_roar' | 'chapter_sting' | 'quest_complete' | 'enemy_alert' | 'knife_slash';

export type MusicId =
  | 'none' | 'title' | 'explore_night' | 'explore_harbour' | 'tension'
  | 'combat_street' | 'combat_boss' | 'victory' | 'ending';

export interface PlaySfxOptions {
  /** World position for 3D panning/attenuation. Omit for 2D (UI) sounds. */
  position?: Vector3;
  volume?: number;
  /** Playback-rate multiplier, 1 = normal. Random ±5% variation is applied automatically. */
  pitch?: number;
}

export interface IAudioSystem {
  /** Must be called from a user gesture (title screen click) to resume the AudioContext. */
  unlock(): Promise<void>;
  playSfx(id: SfxId, opts?: PlaySfxOptions): void;
  /** Crossfade to a music track. Same id = no-op. */
  playMusic(id: MusicId, crossfadeSec?: number): void;
  readonly currentMusic: MusicId;
  /** Temporarily lower music/ambience (dialogue, heat actions). */
  duck(amount: number, realDuration: number): void;
  setVolume(bus: 'master' | 'music' | 'sfx' | 'ambience', value: number): void;
  getVolume(bus: 'master' | 'music' | 'sfx' | 'ambience'): number;
}

// ---------------------------------------------------------------------------
// World
// ---------------------------------------------------------------------------

export type ZoneId = 'percy' | 'hennessy' | 'sogo' | 'typhoon';

export const ZONE_NAMES: Record<ZoneId, { zh: string; en: string }> = {
  percy: { zh: '波斯富街', en: 'Percy Street' },
  hennessy: { zh: '軒尼詩道', en: 'Hennessy Road' },
  sogo: { zh: '崇光百貨', en: 'Sogo Crossing' },
  typhoon: { zh: '避風塘', en: 'Typhoon Shelter' },
};

/**
 * Named anchors that the WORLD module must provide. Narrative, combat and
 * entities reference places ONLY through these ids.
 *
 * Reference layout (world module may refine positions but must keep the topology):
 *  - Hennessy Road runs east-west along z ∈ [0, 24], x ∈ [-150, 150], tram rails at z≈12.
 *  - Percy Street runs north from Hennessy: x ∈ [-72, -56], z ∈ [-130, 0], with side alleys.
 *  - Sogo Crossing is the big junction at the east: x ∈ [50, 110], z ∈ [0, 24]; the Sogo
 *    building occupies the south-east corner (x ∈ [60, 140], z ∈ [24, 80]) and its plaza
 *    (x ∈ [60, 110], z ∈ [24, 44]) is the boss arena.
 *  - The Typhoon Shelter promenade runs east-west at the north: z ∈ [-175, -150],
 *    x ∈ [-150, 60], with water (harbour, sampans) north of z = -175. A footbridge / path
 *    connects the north end of Percy Street (z≈-130) to the promenade.
 */
export type LocationId =
  | 'player_start'            // south end of Percy St, facing north
  | 'percy_curry_fishball'    // 咖喱魚蛋 stall (vendor stands here)
  | 'percy_cha_chaan_teng'    // 冰室 serving 凍檸茶 (vendor/door)
  | 'percy_payphone'
  | 'percy_informant'         // 山雞 hangs out here
  | 'percy_alley'             // side alley where the prologue brawl happens
  | 'percy_north'             // north end of Percy St (Tung Shing territory)
  | 'hennessy_center'
  | 'hennessy_newsstand'      // 報紙檔 / convenience stall (shop)
  | 'hennessy_payphone'
  | 'sogo_crossing'           // centre of the Sogo junction
  | 'sogo_plaza'              // boss arena centre (in front of Sogo)
  | 'sogo_plaza_entry'        // where the player enters the arena
  | 'sogo_payphone'
  | 'sogo_dai_pai_dong'       // outdoor tables next to the plaza (Crow flips these)
  | 'typhoon_entry'           // where the Percy-St path reaches the promenade
  | 'typhoon_promenade'       // middle of the promenade
  | 'typhoon_pier'            // pier with 蝦叔's sampan
  | 'typhoon_payphone'
  | 'typhoon_crab_boat'       // 避風塘炒蟹 floating restaurant (shop)
  | 'substory_pager'          // where the lost pager lies
  | 'substory_debt';          // where the debt collectors lurk

export interface WorldLocation {
  position: Vector3;
  yaw: number;
}

export type HotspotKind = 'vendor' | 'payphone' | 'pickup';

export type HotspotId =
  | 'hs_curry_fishball' | 'hs_cha_chaan_teng' | 'hs_newsstand' | 'hs_crab_boat'
  | 'hs_payphone_percy' | 'hs_payphone_hennessy' | 'hs_payphone_sogo' | 'hs_payphone_typhoon'
  | 'hs_lost_pager';

/**
 * Hotspots are DATA + VISUALS owned by the world (the stall, the payphone
 * booth, the pager lying on the ground). The NARRATIVE module registers the
 * matching IInteractable and decides what happens (shop, save, pick up).
 */
export interface HotspotDef {
  id: HotspotId;
  kind: HotspotKind;
  position: Vector3;
  /** Interaction radius (metres). */
  radius: number;
  /** Prompt label, e.g. '購買', '打電話', '拾起'. */
  label: string;
  /** Shop behind this hotspot (vendor kind only). */
  shopId?: ShopId;
}

/** Where loose weapons lie around the streets. The COMBAT module instantiates them. */
export interface PropSpawn {
  kind: WeaponKind;
  position: Vector3;
  yaw: number;
  zone: ZoneId;
}

export interface TerritoryDef {
  id: string;
  zone: ZoneId;
  /** Axis-aligned XZ rectangle. */
  min: { x: number; z: number };
  max: { x: number; z: number };
  faction: 'tungShing';
  /** Chance (0..1) per 10 s the player spends inside to trigger a random encounter. */
  encounterChance: number;
}

export type TriggerShape =
  | { type: 'sphere'; center: Vector3; radius: number }
  | { type: 'box'; min: Vector3; max: Vector3 };

export interface TriggerDef {
  id: string;
  shape: TriggerShape;
  /** Fire 'trigger:enter' only once, then remove. */
  once?: boolean;
}

export interface MinimapShape {
  kind: 'road' | 'sidewalk' | 'building' | 'water' | 'plaza' | 'rail';
  /** Closed polygon in world XZ (x, z pairs). */
  points: Array<{ x: number; z: number }>;
}

export interface MinimapData {
  bounds: { minX: number; minZ: number; maxX: number; maxZ: number };
  shapes: MinimapShape[];
  labels: Array<{ text: string; x: number; z: number }>;
}

export type WeatherKind = 'clear' | 'drizzle' | 'rain';

/**
 * The walkable world is FLAT at y = 0 (curbs ≤ 0.2 m are handled by autostep).
 * The world registers every static collider itself (ground slab, buildings,
 * barriers, railings, harbour edge, parked vehicles, street furniture) and keeps
 * a 14 m radius around `sogo_plaza` free of colliders (boss arena).
 */
export interface IWorld {
  readonly currentZone: ZoneId;
  readonly weather: WeatherKind;
  readonly bounds: Box3;
  getLocation(id: LocationId): WorldLocation;
  getZoneAt(position: Vector3): ZoneId;
  getHotspots(): readonly HotspotDef[];
  getPropSpawns(): readonly PropSpawn[];
  getTerritories(): readonly TerritoryDef[];
  /** Polylines along sidewalks for ambient pedestrians (y = 0). */
  getPedestrianPaths(): readonly Vector3[][];
  getMinimapData(): MinimapData;
  /**
   * Up to `count` walkable points in a ring [minR, maxR] around `center`,
   * not inside buildings, each with nothing solid on the straight line back
   * to `center` (for enemies stepping out of the crowd).
   */
  getSpawnPoints(center: Vector3, minR: number, maxR: number, count: number): Vector3[];
  /** Is this XZ point walkable (not inside a building / water)? */
  isWalkable(position: Vector3): boolean;
  addTrigger(def: TriggerDef): void;
  removeTrigger(id: string): void;
  setWeather(weather: WeatherKind, transitionSec?: number): void;
  /** Build progress callback while init() runs (0..1). */
  onBuildProgress?: (progress: number, label: string) => void;
}

// ---------------------------------------------------------------------------
// Characters & entities
// ---------------------------------------------------------------------------

export type EntityKind = 'character' | 'prop' | 'effect';
export type CharacterRole = 'player' | 'enemy' | 'boss' | 'npc' | 'vendor' | 'pedestrian';
export type Faction = 'hungHing' | 'tungShing' | 'civilian';

export interface IEntity {
  readonly id: string;
  readonly kind: EntityKind;
  readonly object3d: Object3D;
  /** Same reference as object3d.position. */
  readonly position: Vector3;
  update(time: GameTime): void;
  dispose(): void;
}

export type BoneName =
  | 'hips' | 'spine' | 'chest' | 'neck' | 'head'
  | 'upperArmL' | 'forearmL' | 'handL'
  | 'upperArmR' | 'forearmR' | 'handR'
  | 'thighL' | 'shinL' | 'footL'
  | 'thighR' | 'shinR' | 'footR';

export type Pose = { [B in BoneName]?: [number, number, number] } & {
  rootOffset?: [number, number, number];
};

export interface AnimKeyframe {
  /** Normalised time 0..1. */
  t: number;
  pose: Pose;
  /** Easing used when interpolating FROM this key to the next. */
  ease?: EaseName;
}

export interface AnimClipDef {
  name: string;
  duration: number;
  loop: boolean;
  keys: AnimKeyframe[];
  /** Normalised time of the strike contact (attack clips). */
  impactAt?: number;
}

/**
 * Library clips the ENTITIES module must implement. Attack clips must have
 * `impactAt` defined; combat syncs hit timing to it.
 */
export type AnimClip =
  // locomotion
  | 'idle' | 'walk' | 'run' | 'sprint'
  | 'combatIdle' | 'combatWalkF' | 'combatWalkB' | 'combatWalkL' | 'combatWalkR'
  // social / ambient
  | 'talk' | 'talkAngry' | 'listen' | 'nod' | 'shrug' | 'point' | 'bow' | 'crossArms'
  | 'eat' | 'drink' | 'phone' | 'cheer' | 'cower' | 'flee' | 'lean' | 'smoke' | 'vendorIdle' | 'taunt' | 'sitGround'
  // attacks (impactAt required)
  | 'jab' | 'cross' | 'hook' | 'uppercut' | 'frontKick' | 'roundhouse' | 'spinKick'
  | 'heavyPunch' | 'rushPunch' | 'stomp' | 'dropKick'
  | 'weaponSwing' | 'weaponSwing2' | 'weaponOverhead' | 'weaponThrow'
  | 'grabHold' | 'grabPunch' | 'throwToss'
  // defence / movement
  | 'guard' | 'guardHit' | 'dodgeF' | 'dodgeB' | 'dodgeL' | 'dodgeR'
  // reactions
  | 'hitLight' | 'hitHeavy' | 'hitBack' | 'stagger' | 'knockdown' | 'downed' | 'getUp' | 'ko' | 'grabbed' | 'thrown'
  // misc
  | 'pickup' | 'victory';

export interface PlayAnimOptions {
  /** Override clip duration (seconds); keys are time-scaled to fit. */
  duration?: number;
  /** Cross-fade time in seconds. Default 0.12. */
  blend?: number;
  /** Override looping. */
  loop?: boolean;
  /** Restart even if this clip is already playing. Default true for non-loop clips. */
  restart?: boolean;
}

export interface ICharacterRig {
  readonly root: Object3D;
  readonly currentClip: string;
  /** 0..1 progress of the current non-looping clip (1 when finished). */
  readonly progress: number;
  readonly finished: boolean;
  play(clip: AnimClip | AnimClipDef, opts?: PlayAnimOptions): void;
  getClipDef(clip: AnimClip): AnimClipDef;
  getBone(bone: BoneName): Object3D;
  /** World position of a bone (hands/feet used for hitboxes). */
  getBoneWorldPosition(bone: BoneName, out?: Vector3): Vector3;
  /** Attach an object to a hand socket (weapons). Pass null to detach. */
  attachToHand(hand: 'left' | 'right', obj: Object3D | null): void;
  /** Tint flash (hit feedback), e.g. 0xffffff for 0.08s. */
  flash(color: number, duration: number): void;
  setOutline(on: boolean, color?: number): void;
  update(dt: number): void;
}

export type HairStyle = 'long' | 'short' | 'slick' | 'bald' | 'spiky' | 'perm' | 'bun' | 'crew';
export type TopStyle = 'tshirt' | 'shirt' | 'hawaiian' | 'tank' | 'jacket' | 'leather' | 'suit' | 'apron' | 'vest' | 'singlet';
export type BottomStyle = 'jeans' | 'slacks' | 'shorts' | 'skirt';
export type Accessory = 'sunglasses' | 'goldChain' | 'cigarette' | 'watch' | 'headband' | 'tattooArms' | 'earring' | 'glasses' | 'cap';

export interface CharacterAppearance {
  /** Metres, typical 1.60–1.90. */
  height: number;
  build: 'slim' | 'normal' | 'heavy' | 'muscular';
  skinTone: number;
  hair: HairStyle;
  hairColor: number;
  top: TopStyle;
  topColor: number;
  /** Secondary colour (open shirt undershirt, pattern colour, jacket lining). */
  topAccent?: number;
  bottom: BottomStyle;
  bottomColor: number;
  shoeColor?: number;
  accessories?: Accessory[];
  female?: boolean;
}

export type AppearancePreset =
  | 'hoNam'        // protagonist 陳浩南: long centre-parted black hair, black shirt open over white tee, jeans
  | 'chicken'      // 山雞: bleached spiky hair, loud hawaiian shirt, gold chain
  | 'crow'         // 烏鴉: slicked hair, sunglasses, black leather jacket, red shirt, tattoos — big & muscular
  | 'tsGoonA' | 'tsGoonB' | 'tsGoonC' | 'tsGoonD'   // 東星 thugs (tank tops, floral shirts, bleached hair, headbands)
  | 'tsLieutenant' // 東星 enforcer (tougher mini-boss look)
  | 'vendorAuntie' // 咖喱魚蛋 auntie, apron
  | 'chaChaanTengBoss' | 'newsstandUncle'
  | 'fishermanUncle' // 蝦叔
  | 'debtor' | 'pagerOwner'
  | 'pedestrian';  // randomised civilian

export interface CombatStats {
  /** Multiplier on outgoing damage. */
  power: number;
  /** Multiplier on incoming damage (lower = tougher). */
  defense: number;
  /** Locomotion speed multiplier. */
  speed: number;
  /** Poise: accumulated damage before a heavy stagger (hitstun ignored below this per combo). */
  poise: number;
}

export type CombatState =
  | 'idle' | 'moving' | 'attacking' | 'guarding' | 'dodging'
  | 'hitstun' | 'staggered' | 'airborne' | 'knockdown' | 'downed' | 'gettingUp'
  | 'grabbing' | 'grabbed' | 'heatLocked' | 'ko';

export interface ICharacterBrain {
  update(time: GameTime): void;
  dispose?(): void;
}

/**
 * MOTION OWNERSHIP (the rule that keeps entities/combat/narrative from fighting):
 *  - While `ctx.combat.canMove(c)` is false, COMBAT owns c's desiredVelocity,
 *    facing and animation (attacks, hitstun, knockdown, heat actions...).
 *    Combat must set desiredVelocity itself when it takes over (usually zero).
 *  - Otherwise, an active `moveTo()` owns motion (brain is not ticked meanwhile);
 *  - otherwise the brain / PlayerController owns it.
 *
 * ANIMATION RULE:
 *  - When combatState is 'idle' or 'moving', the Character auto-selects its
 *    locomotion clip every frame from horizontal speed + stance:
 *      stance 'normal': idleClip (still) / walk (<2.2 m/s) / run (<5.5) / sprint
 *      stance 'combat': combatIdle / combatWalkF|B|L|R relative to facing
 *    It will NOT interrupt a non-looping clip that is still playing (a one-shot
 *    'nod', 'pickup', 'drink'...). Once that finishes, locomotion resumes.
 *    To keep an NPC in a looping gesture, set `idleClip` (e.g. 'talk').
 *  - In any other combatState the Character never changes clips on its own.
 */
export interface ICharacter extends IEntity {
  readonly kind: 'character';
  readonly role: CharacterRole;
  readonly faction: Faction;
  readonly displayName: string;
  readonly rig: ICharacterRig;
  readonly body: ICharacterBody;
  readonly radius: number;
  readonly height: number;
  hp: number;
  maxHp: number;
  stats: CombatStats;
  combatState: CombatState;
  /** Seconds in current combatState (combat module resets it). */
  stateTime: number;
  /** Yaw in radians (see conventions). */
  facing: number;
  /** Current persistent desired horizontal velocity (read-only view; use setDesiredVelocity). */
  readonly desiredVelocity: Vector3;
  /** Clip used when standing still in 'normal' stance. */
  idleClip: AnimClip;
  stance: 'normal' | 'combat';
  heldWeapon: IWeaponProp | null;
  brain: ICharacterBrain | null;
  hyperArmor: boolean;
  invulnerable: boolean;
  /** Arbitrary per-module data (e.g. combat AI bookkeeping). */
  readonly userData: Record<string, unknown>;

  isAlive(): boolean;
  getForward(out?: Vector3): Vector3;
  /** Turn towards a point. `maxTurn` limits radians turned this call (omit = snap). */
  faceTowards(point: Vector3, maxTurn?: number): void;
  /**
   * Desired horizontal velocity (m/s) for the next fixed steps. Persistent until
   * changed. The character integrates it with gravity + knockback impulse.
   */
  setDesiredVelocity(v: Vector3): void;
  /** Add an instantaneous velocity (knockback/launch). Horizontal part decays with friction. */
  addImpulse(v: Vector3): void;
  teleport(footPosition: Vector3, yaw?: number): void;
  /**
   * Walk/run in a straight line to `target` (cutscenes & scripted beats).
   * Resolves on arrival (within 0.3 m), when cancelled by another moveTo /
   * teleport, or after `timeoutSec` (default 10). Faces the travel direction.
   */
  moveTo(target: Vector3, speed?: number, timeoutSec?: number): Promise<void>;
  /** Convenience for rig.play(). */
  playAnim(clip: AnimClip | AnimClipDef, opts?: PlayAnimOptions): void;
  /** Capsule used for hit detection (world space). */
  getHurtbox(): { base: Vector3; radius: number; height: number };
  /** Show/hide the whole character (cutscenes). */
  setVisible(visible: boolean): void;
}

export interface CharacterSpawnDef {
  id?: string;
  name: string;
  role: CharacterRole;
  faction: Faction;
  appearance: AppearancePreset | CharacterAppearance;
  position: Vector3;
  yaw?: number;
  maxHp?: number;
  stats?: Partial<CombatStats>;
  /** Idle animation for NPCs/vendors (default 'idle'). */
  idleClip?: AnimClip;
}

/**
 * The ENTITIES module owns: rigs + procedural animation, Character, the
 * PlayerController (the ONLY reader of gameplay input: move/sprint/attacks/
 * dodge/guard/grab/heat/interact/lockOn/cycleTarget, active in freeRoam and
 * combat while playerInputEnabled), ambient pedestrians (may be lightweight
 * non-physics actors, not necessarily returned by getCharacters), NPC idle
 * brains, soft separation, and the 'player' saveable (position, yaw, hp).
 * Player id is 'player'.
 */
export interface IEntityManager {
  /** The protagonist. Always exists after init(). */
  readonly player: ICharacter;
  spawnCharacter(def: CharacterSpawnDef): ICharacter;
  despawn(id: string): void;
  getCharacter(id: string): ICharacter | undefined;
  getCharacters(filter?: { role?: CharacterRole; faction?: Faction; alive?: boolean }): ICharacter[];
  queryRadius(center: Vector3, radius: number, filter?: { role?: CharacterRole; faction?: Faction; alive?: boolean }): ICharacter[];
  /** Ambient crowd density 0..1 (pedestrians flee automatically during combat). */
  setPedestrianDensity(density: number): void;
  /** Player can be moved by input only while this is true AND mode is freeRoam/combat. */
  playerInputEnabled: boolean;
}

// ---------------------------------------------------------------------------
// Interaction
// ---------------------------------------------------------------------------

export interface IInteractable {
  readonly id: string;
  /** Prompt verb shown as "[E] <label>", e.g. '對話', '購買', '拾起 摺凳', '打電話'. */
  readonly label: string;
  /** World position (read every frame, may move). */
  getPosition(): Vector3;
  readonly radius: number;
  /** Modes where this can be used. Default ['freeRoam']. */
  readonly modes?: GameModeId[];
  /** Higher wins ties. Default 0. */
  readonly priority?: number;
  isEnabled(): boolean;
  interact(): void;
}

export interface IInteractionRegistry {
  register(i: IInteractable): void;
  unregister(id: string): void;
  /** Best interactable for the player right now (null if none). Updated each frame. */
  readonly current: IInteractable | null;
  /** Called by the player controller when 'interact' is pressed. Returns true if something was triggered. */
  tryInteract(): boolean;
}

// ---------------------------------------------------------------------------
// Combat
// ---------------------------------------------------------------------------

export type CombatAction =
  | 'light' | 'heavy' | 'dodge' | 'guardStart' | 'guardEnd' | 'grab' | 'heat' | 'throwWeapon' | 'dropWeapon';

export type EncounterId =
  | 'prologue_alley'   // tutorial brawl vs 3 東星 goons at percy_alley
  | 'typhoon_ambush'   // 4 goons + lieutenant at typhoon_promenade
  | 'sogo_goons'       // wave of goons before the boss
  | 'sogo_boss'        // 烏鴉哥 3-phase boss at sogo_plaza
  | 'substory_debt'    // 2 debt collectors
  | 'random_street';   // territory random encounter (2-4 goons)

export interface EncounterResult {
  encounterId: EncounterId;
  victory: boolean;
  moneyEarned: number;
}

export type WeaponKind = 'folding_chair' | 'traffic_cone' | 'beer_bottle' | 'wooden_stool';

export interface IWeaponProp extends IEntity {
  readonly kind: 'prop';
  readonly weaponKind: WeaponKind;
  readonly displayName: string;
  durability: number;
  readonly maxDurability: number;
  holder: ICharacter | null;
}

/**
 * The combat module owns: hit rules, damage, heat, enemy/boss AI brains,
 * encounters, weapons (instantiated from world.getPropSpawns() and registered
 * as interactables usable in ['freeRoam','combat'], label '拾起 <name>'),
 * heat actions, the boss arena tables, combat VFX, player death detection
 * (emits 'player:died'), post-fight money rewards (via ctx.inventory.addMoney).
 *
 * Enemies are spawned with ids 'enemy_<n>'; the boss is 'boss_crow'. After an
 * encounter, defeated enemies lie on the ground ~8 s and are despawned, EXCEPT
 * the boss, which stays (combatState 'ko') until the narrative despawns it.
 */
export interface ICombatSystem {
  readonly inCombat: boolean;
  readonly encounterId: EncounterId | null;
  readonly lockTarget: ICharacter | null;
  readonly heat: number;
  readonly maxHeat: number;
  /** A heat action is currently possible (UI shows the [F] prompt). */
  readonly heatActionAvailable: { nameZh: string; nameEn: string } | null;
  /**
   * Spawn the encounter's enemies without starting the fight (for pre-fight
   * cutscenes: they stand idle, brains inactive). Idempotent; returns them.
   */
  prepareEncounter(id: EncounterId): ICharacter[];
  /**
   * Start the fight: uses prepared enemies if any, otherwise spawns them.
   * Transitions the game state to 'combat'.
   */
  startEncounter(id: EncounterId): void;
  /** Resolves when the given encounter ends. */
  waitForEncounter(id: EncounterId): Promise<EncounterResult>;
  /**
   * Ask the combat rules to perform an action for a character. Returns false if
   * refused. Actions are contextual: e.g. 'light' while grabbing = grab punch,
   * 'heavy' while grabbing = throw, 'light' with a weapon = weapon swing.
   * 'dodge' direction comes from c.desiredVelocity (zero = back-step).
   * Buffering: a request during an attack is queued for the combo (one slot; a hit clears it).
   */
  requestAction(c: ICharacter, action: CombatAction): boolean;
  /** Q: lock onto the best target in front of the player / release lock. */
  toggleLockOn(): void;
  /** Tab: next target. */
  cycleLockTarget(): void;
  /** Can this character currently be steered by locomotion input/AI? */
  canMove(c: ICharacter): boolean;
  getActiveEnemies(): ICharacter[];
  addHeat(amount: number): void;
  /** Territory random encounters on/off (narrative disables during story beats). */
  setRandomEncountersEnabled(enabled: boolean): void;
  /** Weapons currently lying in the world / held. */
  getWeapons(): readonly IWeaponProp[];
}

// ---------------------------------------------------------------------------
// Inventory & economy
// ---------------------------------------------------------------------------

export type ItemId =
  | 'curry_fishball' | 'siu_mai' | 'cart_noodles' | 'egg_waffle' | 'pineapple_bun'
  | 'lemon_tea_iced' | 'milk_tea' | 'yuenyeung' | 'vitasoy' | 'beer'
  | 'typhoon_crab' | 'first_aid_plaster' | 'tiger_balm'
  | 'pager_lost' | 'debt_iou';

export type ShopId = 'shop_curry_fishball' | 'shop_cha_chaan_teng' | 'shop_newsstand' | 'shop_crab_boat';

export interface ItemDef {
  id: ItemId;
  nameZh: string;
  nameEn: string;
  kind: 'food' | 'drink' | 'medicine' | 'key';
  /** Price in HKD. 0 for key items. */
  price: number;
  /** HP restored when consumed. */
  heal?: number;
  /** Heat gained when consumed. */
  heat?: number;
  descZh: string;
}

export interface ShopDef {
  id: ShopId;
  nameZh: string;
  nameEn: string;
  /** Greeting line from the vendor. */
  greetingZh: string;
  items: ItemId[];
}

export interface IInventory {
  readonly money: number;
  addMoney(amount: number): void;
  /** Returns false (no change) if not enough money. */
  spendMoney(amount: number): boolean;
  getItems(): ReadonlyArray<{ id: ItemId; count: number }>;
  count(id: ItemId): number;
  addItem(id: ItemId, count?: number): void;
  removeItem(id: ItemId, count?: number): boolean;
  /** Consume a food/drink/medicine: heals player, adds heat, plays sfx. */
  useItem(id: ItemId): boolean;
  getItemDef(id: ItemId): ItemDef;
  getShop(id: ShopId): ShopDef;
  /** Buy one item. If `consumeNow`, it is eaten on the spot (Yakuza style) instead of stored. */
  buy(shop: ShopId, item: ItemId, consumeNow: boolean): boolean;
}

// ---------------------------------------------------------------------------
// Narrative
// ---------------------------------------------------------------------------

export type QuestKind = 'main' | 'substory';

export interface QuestMarker {
  id: string;
  kind: 'main' | 'substory' | 'shop' | 'save';
  position: Vector3;
  label?: string;
}

export interface QuestView {
  id: string;
  kind: QuestKind;
  titleZh: string;
  titleEn: string;
  status: 'locked' | 'available' | 'active' | 'completed';
  /** Current objective text (Traditional Chinese). */
  objectiveZh: string;
  descriptionZh: string;
}

/**
 * The NARRATIVE module owns: story progression (chapters, quests, flags),
 * dialogue scripts + DialogueManager, cutscenes, all named NPCs (山雞, 蝦叔,
 * vendors, substory NPCs — ids 'npc_*'), the IInteractables for NPCs and world
 * hotspots (shops → state 'shop' + ui.openShop; payphones → save), quest
 * markers, story triggers, autosaves before story fights, enabling/disabling
 * random encounters. Story beats are RE-ENTRANT: after save.load() the player
 * is placed at the saved spot and the current beat re-fires from its trigger.
 * If an awaited encounter returns victory=false (player died), the beat just
 * returns — the game-over flow in GameInstance takes over.
 */
export interface INarrative {
  /** Title → new game: resets state, plays the intro, lands in freeRoam. */
  startNewGame(): Promise<void>;
  /** Continue from the save system's loaded data. */
  continueGame(): Promise<void>;
  startDialogue(dialogueId: string): Promise<void>;
  playCutscene(cutsceneId: string): Promise<void>;
  getQuests(): QuestView[];
  getActiveMarkers(): QuestMarker[];
  /** Currently tracked main objective (HUD top-right). */
  getTrackedObjective(): { titleZh: string; objectiveZh: string } | null;
  getFlag(key: string): boolean | number | string | undefined;
  setFlag(key: string, value: boolean | number | string): void;
}

// ---------------------------------------------------------------------------
// UI
// ---------------------------------------------------------------------------

export interface DialogueLineView {
  /** Speaker display name, e.g. '山雞'. Empty string = narration. */
  speaker: string;
  /** Traditional Chinese Cantonese line. */
  text: string;
  /** Optional English gloss shown small underneath. */
  gloss?: string;
  /** Name plate colour. */
  speakerColor?: string;
  choices?: Array<{ text: string; disabled?: boolean }>;
}

/**
 * The UI module owns all DOM (in #ui-root): HUD (HP, heat gauge, money,
 * minimap radar, objective, [E] prompt, lock-on reticle, enemy HP bars,
 * damage numbers), dialogue box, menus, screens, QTE, toasts, debug overlay
 * (F3). It reads 'pause' / 'inventory' in freeRoam/combat and opens the pause
 * menu itself (state 'menu', state.back() on close). HUD data is PULLED from
 * ctx every frame. Screen-space projections happen in lateUpdate.
 */
export interface IUIManager {
  /**
   * Show a dialogue line (typewriter). Resolves when the player advances (-1) or
   * picks a choice (index). Handles its own input (E/Space/Enter/click, W/S/1-4).
   */
  presentLine(line: DialogueLineView): Promise<number>;
  hideDialogue(): void;
  showSubtitle(text: string, speaker?: string, durationSec?: number): void;
  toast(text: string, kind?: 'info' | 'money' | 'item' | 'quest' | 'warning'): void;
  showLocationBanner(zone: ZoneId): void;
  /** Big chapter card, e.g. ('第一章', '波斯富街'). */
  showChapterTitle(chapter: string, title: string, subtitleEn?: string): Promise<void>;
  showHeatActionName(nameZh: string, nameEn: string): void;
  showBossBar(name: string, title: string): void;
  hideBossBar(): void;
  /** QTE prompt; resolves true on success. Handles its own input. */
  runQTE(keys: InputAction[], windowSec: number): Promise<boolean>;
  /** Shop menu for a shop; resolves when closed. */
  openShop(shop: ShopId): Promise<void>;
  openPauseMenu(tab?: 'inventory' | 'quests' | 'system'): void;
  closePauseMenu(): void;
  /** Title screen; resolves with the chosen option (after a user gesture). */
  showTitleScreen(hasSave: boolean): Promise<'new' | 'continue'>;
  showGameOver(): Promise<'retry' | 'title'>;
  showCredits(): Promise<void>;
  setLetterbox(on: boolean): void;
  fade(toBlack: boolean, durationSec: number): Promise<void>;
  setHudVisible(visible: boolean): void;
  showLoading(progress: number, label: string): void;
  hideLoading(): void;
}

// ---------------------------------------------------------------------------
// Save
// ---------------------------------------------------------------------------

export interface ISaveable {
  readonly saveKey: string;
  serialize(): unknown;
  deserialize(data: unknown): void;
  /** Reset to new-game state. */
  reset(): void;
}

export interface SaveMeta {
  version: number;
  timestamp: number;
  chapterZh: string;
  locationZh: string;
  playTimeSec: number;
}

export interface ISaveSystem {
  register(saveable: ISaveable): void;
  save(meta: Omit<SaveMeta, 'version' | 'timestamp' | 'playTimeSec'>): void;
  /** Load into all registered saveables. Returns false if no valid save. */
  load(): boolean;
  hasSave(): boolean;
  getMeta(): SaveMeta | null;
  /** Reset all saveables to new-game state. */
  resetAll(): void;
  readonly playTimeSec: number;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

export interface HitEvent {
  attackerId: string;
  targetId: string;
  damage: number;
  position: Vector3;
  kind: 'light' | 'heavy' | 'weapon' | 'heat' | 'throw' | 'environment';
  blocked: boolean;
  /** Target was knocked down / launched by this hit. */
  knockdown: boolean;
}

export interface GameEvents {
  'state:changed': { from: GameModeId; to: GameModeId; payload: unknown };
  'zone:changed': { from: ZoneId | null; to: ZoneId };
  'trigger:enter': { triggerId: string };
  'trigger:exit': { triggerId: string };
  'interact:changed': { interactable: IInteractable | null };

  'player:hp': { hp: number; maxHp: number; delta: number };
  'player:died': Record<string, never>;

  'combat:start': { encounterId: EncounterId; enemyIds: string[]; isBoss: boolean };
  'combat:end': EncounterResult;
  'combat:hit': HitEvent;
  'combat:ko': { characterId: string; byId: string };
  'combat:lockTarget': { targetId: string | null };
  'heat:changed': { heat: number; maxHeat: number };
  'heat:action': { actionId: string; nameZh: string; nameEn: string; targetId: string };
  'weapon:pickup': { weaponId: string; kind: WeaponKind; characterId: string };
  'weapon:broken': { weaponId: string; kind: WeaponKind };
  'boss:phase': { bossId: string; phase: number };
  'boss:hp': { bossId: string; hp: number; maxHp: number };
  'qte:result': { success: boolean };

  'money:changed': { money: number; delta: number };
  'item:changed': { id: ItemId; count: number; delta: number };

  'dialogue:start': { dialogueId: string };
  'dialogue:end': { dialogueId: string };
  'cutscene:start': { cutsceneId: string };
  'cutscene:end': { cutsceneId: string };
  'quest:updated': { questId: string; status: QuestView['status']; objectiveZh: string };
  'quest:completed': { questId: string; kind: QuestKind };
  'chapter:start': { chapter: number; titleZh: string };

  'save:done': { meta: SaveMeta };
  /** save() could not write (a saveable threw, or storage is full/denied); nothing was written. */
  'save:failed': Record<string, never>;
  'game:newGame': Record<string, never>;
  'game:loaded': Record<string, never>;
}

// ---------------------------------------------------------------------------
// Composition
// ---------------------------------------------------------------------------

export interface GameContext {
  readonly engine: IEngine;
  readonly events: EventBus<GameEvents>;
  readonly input: IInputManager;
  readonly state: IGameStateMachine;
  readonly physics: IPhysicsWorld;
  readonly cameraRig: ICameraRig;
  readonly interactions: IInteractionRegistry;
  readonly audio: IAudioSystem;
  readonly world: IWorld;
  readonly entities: IEntityManager;
  readonly combat: ICombatSystem;
  readonly inventory: IInventory;
  readonly narrative: INarrative;
  readonly ui: IUIManager;
  readonly save: ISaveSystem;
  /** URL flags: ?debug, ?chapter=N, ?skipIntro, ?god */
  readonly debug: { enabled: boolean; chapter: number | null; skipIntro: boolean; god: boolean };
}
